stages:
- build
- test
- sonarqube-check

build:
  stage: build
  script:
    - cd VideoGameStore
    - ./gradlew build

test:
  stage: test
  script:
     - cd VideoGameStore
     - ./gradlew test
sonarqube-check:
  stage: sonarqube-check
  script:
    - cd VideoGameStore
    - ./gradlew tasks --all
