stages:
- build
- test
- sonarqube-check

build:
  stage: build
  script:
    - cd VideoGameStore
    - ./gradlew build

test:
  stage: test
  script:
     - cd VideoGameStore
     - ./gradlew test
sonarqube-check:
  script:
    - cd VideoGameStor
    - gradle sonarqube -D"sonar.qualitygate.wait=true" -D"sonar.login=eaffffbef98d5602fa9087660b38ac09a251f281" -D"sonar.host.url=http://localhost:9000"
