stages:
- build
- test

build:
  image: gradle:7.1.1
  stage: build
  script:
    - VideoGameStore/gradlew build -x test

test:
  image: gradle:7.1.1
  stage: test
  script:
    - VideoGameStore/gradlew test
